<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Category;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Map category slugs to database IDs
        $categoryMap = Category::pluck('id', 'slug')->toArray();

        $products = [
            [
                'id' => 1,
                'category_id' => $categoryMap['drinks'],
                'name' => 'Classic Cappuccino',
                'description' => 'Rich espresso combined with steamed milk and a deep layer of thick foam. A true classic topped with a sprinkle of cocoa powder.',
                'price' => 150.00,
                'rating' => 4.8,
                'reviews' => 124,
                'is_popular' => true,
                'image' => 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'category_id' => $categoryMap['drinks'],
                'name' => 'Caramel Macchiato',
                'description' => 'Freshly steamed milk with vanilla-flavored syrup marked with freshly pulled espresso and drizzled with rich caramel.',
                'price' => 180.00,
                'rating' => 4.9,
                'reviews' => 248,
                'is_popular' => true,
                'image' => 'https://images.unsplash.com/photo-1541167760496-1628856ab772?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'category_id' => $categoryMap['drinks'],
                'name' => 'Vanilla Sweet Cream Cold Brew',
                'description' => 'Slow-steeped cold brew served over ice and topped with a splash of handcrafted vanilla sweet cream that floats down.',
                'price' => 170.00,
                'rating' => 4.9,
                'reviews' => 312,
                'is_popular' => true,
                'image' => 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'category_id' => $categoryMap['drinks'],
                'name' => 'Spanish Latte',
                'description' => 'A smooth blend of espresso and condensed milk — creamy, lightly sweet, and deeply satisfying.',
                'price' => 155.00,
                'rating' => 4.8,
                'reviews' => 211,
                'is_popular' => true,
                'image' => 'https://images.unsplash.com/photo-1485808191679-5f86510bd9d4?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'category_id' => $categoryMap['drinks'],
                'name' => 'Iced Americano',
                'description' => 'Bold double-shot espresso poured over ice and a splash of cold water. Clean, crisp, and refreshing.',
                'price' => 110.00,
                'rating' => 4.7,
                'reviews' => 188,
                'is_popular' => false,
                'image' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'category_id' => $categoryMap['drinks'],
                'name' => 'Gold Espresso Macchiato',
                'description' => 'Double-shot heritage Barako espresso layered with wild honey and vanilla oat milk.',
                'price' => 195.00,
                'rating' => 5.0,
                'reviews' => 42,
                'is_popular' => true,
                'image' => 'https://images.unsplash.com/photo-1570968915860-54d5c301fc9f?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'category_id' => $categoryMap['foods'],
                'name' => 'Classic Butter Croissant',
                'description' => 'Warm, flaky French butter pastry baked fresh daily. The perfect companion to a hot cup of espresso.',
                'price' => 95.00,
                'rating' => 4.8,
                'reviews' => 184,
                'is_popular' => true,
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'category_id' => $categoryMap['foods'],
                'name' => 'Clubhouse Sandwich',
                'description' => 'Triple-decker sandwich layered with grilled chicken, scrambled egg, crispy bacon, lettuce, tomato, and light mayo.',
                'price' => 180.00,
                'rating' => 4.7,
                'reviews' => 115,
                'is_popular' => false,
                'image' => 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'category_id' => $categoryMap['foods'],
                'name' => 'Classic Waffle',
                'description' => 'Golden crispy waffle served with butter, maple syrup, and a dusting of powdered sugar.',
                'price' => 95.00,
                'rating' => 4.6,
                'reviews' => 98,
                'is_popular' => false,
                'image' => 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'category_id' => $categoryMap['desserts'],
                'name' => 'Blueberry Cheesecake Slice',
                'description' => 'Rich, smooth, and creamy cream cheese filling on a graham cracker crust, topped with sweet blueberry compote.',
                'price' => 160.00,
                'rating' => 4.9,
                'reviews' => 196,
                'is_popular' => true,
                'image' => 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'category_id' => $categoryMap['desserts'],
                'name' => 'Chocolate Cookie',
                'description' => 'Freshly baked, soft-centered dark chocolate chip cookie with a crispy edge. Pairs perfectly with any brew.',
                'price' => 65.00,
                'rating' => 4.7,
                'reviews' => 143,
                'is_popular' => false,
                'image' => 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'category_id' => $categoryMap['pasalubong'],
                'name' => 'Lesh Special Ube Hopia Box',
                'description' => 'A box of traditional flaky pastries filled with rich, sweet purple yam (Ube) paste. A taste of home and heritage.',
                'price' => 220.00,
                'rating' => 4.9,
                'reviews' => 340,
                'is_popular' => true,
                'image' => 'https://images.unsplash.com/photo-1628113401569-4e784534f3c7?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'category_id' => $categoryMap['pasalubong'],
                'name' => 'Barako Coffee Beans Bag (250g)',
                'description' => 'Premium whole coffee beans locally sourced from Batangas. Strong, bold flavor profile with fruity and sweet aroma.',
                'price' => 350.00,
                'rating' => 4.8,
                'reviews' => 175,
                'is_popular' => false,
                'image' => 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'category_id' => $categoryMap['pasalubong'],
                'name' => 'Heritage Polvoron Box',
                'description' => 'Assorted flavors of traditional toasted flour, milk, and butter treats. Crumbly, sweet, and melts in the mouth.',
                'price' => 180.00,
                'rating' => 4.7,
                'reviews' => 108,
                'is_popular' => false,
                'image' => 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=600&auto=format&fit=crop',
                'is_customizable' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}
